parameters:
#    flight_monitor.example.class: Handy\FlightMonitorBundle\Example

services:
#    flight_monitor.example:
#        class: %flight_monitor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
