ubiquitous_music:
    resource: "@UbiquitousMusicBundle/Resources/config/routing.yml"
    prefix:   /

flight_monitor:
    resource: "@FlightMonitorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
