parameters:
#    ubiquitous_music.example.class: Handy\UbiquitousMusicBundle\Example

services:
#    ubiquitous_music.example:
#        class: %ubiquitous_music.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
