trip:
    path:     /
    defaults: { _controller: "FlightMonitorBundle:Trip:index" }

trip_show:
    path:     /{id}/show
    defaults: { _controller: "FlightMonitorBundle:Trip:show" }

trip_new:
    path:     /new
    defaults: { _controller: "FlightMonitorBundle:Trip:new" }

trip_create:
    path:     /create
    defaults: { _controller: "FlightMonitorBundle:Trip:create" }
    requirements: { _method: post }

trip_edit:
    path:     /{id}/edit
    defaults: { _controller: "FlightMonitorBundle:Trip:edit" }

trip_update:
    path:     /{id}/update
    defaults: { _controller: "FlightMonitorBundle:Trip:update" }
    requirements: { _method: post|put }

trip_delete:
    path:     /{id}/delete
    defaults: { _controller: "FlightMonitorBundle:Trip:delete" }
    requirements: { _method: post|delete }
    
trip_monitor:
    path:     /monitor
    defaults: { _controller: "FlightMonitorBundle:Trip:monitor" }
    
trip_report:
    path:     /report/{id}
    defaults: { _controller: "FlightMonitorBundle:Trip:report" }

