musicitem:
    path:     /
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:index" }

musicitem_show:
    path:     /{id}/show
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:show" }

musicitem_new:
    path:     /new
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:new" }

musicitem_create:
    path:     /create
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:create" }
    requirements: { _method: post }

musicitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:edit" }

musicitem_update:
    path:     /{id}/update
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:update" }
    requirements: { _method: post|put }

musicitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbiquitousMusicBundle:MusicItem:delete" }
    requirements: { _method: post|delete }
